classes:
    0: 'Unknown'
    1: 'Almonds'
    2: 'Corn,Sorghum or Sudan grouped for remote sensing only'
    3: 'Land not cropped the current or previous crop season, but cropped within the past three years'
    4: 'Alfalfa & alfalfa mixtures'
    5: 'Pistachios'
    6: 'Mixed pasture'
    7: 'Walnuts'
    8: 'Long term, land consistently idle for four or more years'
    9: 'Miscellaneous grain and hay'
    10: 'Rice'
    11: 'Wheat'
    12: 'Tomato (processing and market)'
    13: 'Miscellaneous grasses'
    14: 'Native pasture'
    15: 'Cotton'
    16: 'Lettuce or Leafy Greens grouped for remote sensing only'
    17: 'Miscellaneous truck'
    18: 'Golf course – irrigated'
    19: 'Cole crops (mixture of 22-25)'
    20: 'Onions & garlic'
    21: 'Peaches and nectarines'
    22: 'Melons, squash, and cucumbers (all types)'
    23: 'Olives'
    24: 'Avocados'
    25: 'Safflower'
    26: 'Strawberries'
    27: 'Prunes'
    28: 'Cherries'
    29: 'Carrots'
    30: 'Sunflowers'
    31: 'Flowers, nursery & Christmas tree farms'
    32: 'Potatoes'
    33: 'Pomegranates'
    34: 'Bush berries'
    35: 'Sweet potatoes'
    36: 'Miscellaneous deciduous'
    37: 'Sugar beets'
    38: 'Plums'
    39: 'Dates'
    40: 'Eucalyptus'
    41: 'Beans (dry)'
    42: 'Wild Rice'
    43: 'Turf farms'
    44: 'Peppers (chili, bell, etc.)'
    45: 'Pears'
    46: 'Apples'
    47: 'Pecans'
    48: 'Kiwis'
    49: 'Apricots'
    50: 'Greenhouse'
    51: 'Induced high water table native pasture'
    52: 'Miscellaneous field'
    53: 'Miscellaneous subtropical fruit'


    

    

colormaps:
  0: [0, 0, 0]
  1: [0, 0, 255]
sample_requirements:
  1: 1  # January
  2: 1  # February
  3: 1  # March
  4: 2  # April
  5: 2  # May
  6: 2  # June
  7: 2  # July
  8: 2  # August
  9: 2  # September
  10: 1 # October
  11: 1 # November
  12: 1  # December

bands:
    "10m": ["B2", "B3", "B4", "B8"] # 10m resolution
    "20m": ["B5", "B6", "B7", "B8A", "B11", "B12"] # 20m resolution
    "SCL": ["SCL"] # 20m resolution